name: customer_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^7.2.0
  flutter_bloc: ^9.1.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  equatable: ^2.0.7
  googleapis_auth: ^1.4.1  # 👈 ADD THIS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true