// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjH3TE-n88nlQr5inY0RgP4NOxPXt4-Q',
    appId: '1:812333354318:web:a13b18ce1838cf454e621f',
    messagingSenderId: '812333354318',
    projectId: 'cinemaapps-5f65f',
    authDomain: 'cinemaapps-5f65f.firebaseapp.com',
    storageBucket: 'cinemaapps-5f65f.firebasestorage.app',
    measurementId: 'G-XWC3LX1B6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeBpj2TcV4bpEnEBCT41VsOKfE-Yc02w',
    appId: '1:812333354318:android:d430124e1b3a73294e621f',
    messagingSenderId: '812333354318',
    projectId: 'cinemaapps-5f65f',
    storageBucket: 'cinemaapps-5f65f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkPlZ3VEYXMxgrt-SyOubSyk5LgEOrP3o',
    appId: '1:812333354318:ios:8f111ef41df798de4e621f',
    messagingSenderId: '812333354318',
    projectId: 'cinemaapps-5f65f',
    storageBucket: 'cinemaapps-5f65f.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkPlZ3VEYXMxgrt-SyOubSyk5LgEOrP3o',
    appId: '1:812333354318:ios:8f111ef41df798de4e621f',
    messagingSenderId: '812333354318',
    projectId: 'cinemaapps-5f65f',
    storageBucket: 'cinemaapps-5f65f.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwjH3TE-n88nlQr5inY0RgP4NOxPXt4-Q',
    appId: '1:812333354318:web:fd947d5f1171f2a74e621f',
    messagingSenderId: '812333354318',
    projectId: 'cinemaapps-5f65f',
    authDomain: 'cinemaapps-5f65f.firebaseapp.com',
    storageBucket: 'cinemaapps-5f65f.firebasestorage.app',
    measurementId: 'G-PRKYWC0GXT',
  );
}
